kafka:
    consumer:
        auto:
            commit:
                interval: 100
            offset:
                reset: latest
        concurrency: 10
        enable:
            auto:
                commit: true
        group:
            id: test
        servers: 127.0.0.1:9092
        session:
            timeout: 6000
        topic: test
        zookeeper:
            connect: 127.0.0.1:2181
    producer:
        batch:
            size: 4096
        buffer:
            memory: 40960
        linger: 1
        retries: 0
        servers: 127.0.0.1:9092
mybatis:
    mapperLocations: classpath:mappers/*.xml
    typeAliasesPackage: ''
server:
    port: 7001
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379

socketServer:
  socketPort: 8888
  webSocketPort: 9999
